name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          # context: This is the directory where your app lives.
          # Docker will look here for requirements.txt and app.py
          context: ./smart-library
          
          # file: The path to the Dockerfile relative to the repo root
          file: ./smart-library/Dockerfile
          
          push: true
          
          # tags: We use lowercase here to avoid registry errors.
          # This will name your package "flask-library-app"
          tags: |
            ghcr.io/${{ github.repository_owner }}/flask-library-app:latest

